---
title: "Complaints Assignment Tinsley"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
options(tigris_use_cache = TRUE)
library(flexdashboard)
library(tidyverse)
library(tidyverse)
library(lubridate)
library(readxl)
library(janitor)
library(glue)
library(leaflet)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(tigris)
library(tmap)
library(tmaptools)
library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Complaints by Product

```{r}
# Data Preparation

complaints_data <- readRDS("complaints.rds")

complaints_counted <- complaints_data %>%
    arrange(company) %>% 
    count(product) 

complaints_counted
```


```{r}
#Data Visualisation
byproduct_fig <- plot_ly(data = complaints_counted, labels = ~product, values = ~n)

byproduct_fig <- byproduct_fig %>% add_pie(hole = 0.6) #would make a pie chart, to make a donut chart add the hole

byproduct_fig <- byproduct_fig %>% layout(
                  title = "Number of Complaints by Product",  showlegend = F,
                  xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

byproduct_fig 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Companies with the Most Credit and Consumer Reports Complaints

```{r}
credit_complaints <- complaints_data %>%
    filter(product == "Credit reporting, credit repair services, or other personal consumer reports") %>% 
    count(company) %>% 
    filter(n>20000)
```


```{r}

  


credit_bar <- plot_ly(data = credit_complaints,                    #create a bar chart from it
        x = ~company,
        y = ~n,
        type = "bar"
        ) %>% 
  layout(title = "Most Credit and Consumer Reports Complaints by Company",
         xaxis = list(title = "Company"),
         yaxis = list (title = "Number of Debt Collection Complaints"))

credit_bar
```

### Experian Customer Responses

```{r}
experian_responses <- complaints_data %>%
    filter(company == "Experian Information Solutions Inc.") %>% 
    group_by(company_response_to_consumer) %>% 
    count(company_response_to_consumer)

experian_responses
```


```{r}

experian_bar <- plot_ly(data = experian_responses,                    #create a bar chart from it
        x = ~company_response_to_consumer,
        y = ~n,
        type = "bar"
        ) %>% 
  layout(title = "Experian Responses to Consumer Complaints",
         xaxis = list(title = "Response"),
         yaxis = list (title = "Number"))

experian_bar


```

